### ISSUE TITLE
Mario Teaches Typing 2 (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#1]
If you start the game, select new student, create a character (I chose Mario), select step by step. When gameplay should start it gives:

![image](https://user-images.githubusercontent.com/67406191/101123343-c3798b80-3648-11eb-9240-3a870e811c3f.png)

followed by:

![image](https://user-images.githubusercontent.com/67406191/101123357-d12f1100-3648-11eb-9825-dacf4f841cde.png)

It seems that if we switch back to runmario.exe these errors go away. We had switched to winmario.exe as runmario didnt work with runexit. Here is the original error report:

Python27/09/2019
@eXo Mario Teaches Typing 2: A major and a minor thing for this game. The minor thing is there is no longer an exit command at the bottom of the conf. The major thing is that the game doesnt load from the launch bat. It starts windows, the company logo animation plays, then it drops to prompt. It seems to be an issue with runexit. Two solutions: first, there is another exe, "winmario.exe", that seems to work with runexit. Not sure whats different with this exe though. The other solution is to not use runexit.

**Comment by exoscoriae** [comment]
switched

**Comment by Python-Exoproject** [comment]
Are we still adding user notes to tell the user to press ctrl-f9 to exit for games that dont autoexit?

**Comment by exoscoriae** [comment]
not usually. Because do they even know to hit "exit" from the windows program manager? At some point I think it is better to make a "quick reference card" for win3x in general. and probably eXoDOS. It could be attached to that entry in launchbox. 

It basically says:
For multiple cd games, press Ctrl-F9 to switch discs.
To exit DOSBox at anytime, press Ctrl-F9

Makes a lot more sense than repeatedly adding that note to hundreds of games....
