### ISSUE TITLE
Sonic's Schoolhouse (1997)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#29]
Game crashes when you move forward and click on Sonic

**Comment by exoscoriae** [comment]
fixed. had to make several manual tweaks to the ini files in windows, as well as shift to a VHD.

**Comment by Python-Exoproject** [comment]
Game has choppy sound for me in current Daum setup. Does it do that for you? I switched to X for a test and it ran smooth there for me, even when I switched the game to pentium by clicking the signpost in the bottom right of the user name selection screen.

**Comment by exoscoriae** [comment]
I tested Pentium on and off and saw no difference.

If we switch to X, then you should notice an error during boot, claiming the CSP could not be detected. This can be fixed by adding
enable asp=true
under the [sbalster] section.

Before I did this, it actually ran very poorly for me. After though, it seemed fine. I've converted it to X and modified the conf accordingly.

Do we need to change the outputs now that it is an X game?

**Comment by Python-Exoproject** [comment]
Intertesting, it worked out of the box for me in X.

Need to change to the usual dosbox x output=openglnb, fullresolution=desktop

**Comment by exoscoriae** [comment]
conf modified.
