### ISSUE TITLE
American Civil War - From Sumter to Appomattox (1996)

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#43]
We had issues with the CD rip. Ill note the original issues here:

--------------------------------------------------------------------------------
"I have noticed an interesting issue with cd tracks in "American Civil War". You can play the games cd tracks from an internal player found under the "settings" "music\sound" menus once your in a mission (its actually the only way to get the music to start, theres no auto play). 

First thing I noticed is that it lists 15 tracks in text at the bottom of the player, but 17 are selectable to play (which matches the cue file). The first is the data track which brings it to 16 tracks. I found that the extra track is listed in this internal player as track 3 as its a repeat of track 2 but starting a few seconds into the track.

The second thing I noticed is that when you select track 16 it highlights and plays track 10, and when you select track 17 it plays track 11."

This was all mostly fixed by a few tricks by Spectre and myself leaving the situation as:

"For my first point there are now 16 selectable tracks with the data track being the extra track, not sure if its possible to get the games inbuilt player to ignore the first track.

For my second point it still highlights track 10 when you select track 16. This is most likely due to the issue of track 1 being the data track. At least now track 16 despite showing that its playing track 10 is actually playing the final track of the cd."

-----------------------------------------------------------------

At the time you bought a copy of the CD. Did the CD ever arrive and did it fix the above issues?

**Comment by exoscoriae** [comment]
The first thing I notice is the copy I purchased is only 1 cd, not two. However the "Fateful Lightning" feature from that second disc is included on the first disc.

Second, the cd does not have actual cd tracks. While CD 2 of the version we previously had *did* have CD tracks.

Starting the game in a new copy of windows leads to the intro, however the intro appears to be unskippable. Attempts to hit ESC are met with a crash. Allowing the entire intro to play, also ends with a crash.

Starting the game with the new cd in the old install does work. So we must have modified the windows install somehow back then, but I don't remember how. Any notes would be appreciated on that.

That said, the music player shows no tracks with the new cd due to it not having any tracks.... As the jewelcase is clearly designed for a single cd release, I have no idea what happened here. I thought maybe they had digited the cd audio, but it clearly sees nothing.

That said, the readme specifically states:
"On some Windows 3.1 based systems, the CD player included with
American Civil War may not function correctly.  In this event,
any Windows audio CD player can be used to listen to the music
while playing the game.  Remember to skip the first track."

So, if that is the only issue with our game previously, then I think I would leave it alone and call it a day.

I am curious what was done in windows however that allows the game to run.

**Comment by Python-Exoproject** [comment]
I found this in our discord chatlog:

Python 12/01/2020
@eXo American Civil War: From Sumter to Appomattox: Did you get a black screen after the intro and title screen? If I press nothing it goes through the intro, to the title screen and then loops credits so I have to press enter or space to get it to do something. As soon as I do Im given a black screen that goes nowhere

eXo 16/01/2020
American Civil War was a pain in the ass, but I fixed it
it had debugging left turned on in the games code
running it unde a true windows 3.x \ does 6.22 install gives the error code "cannot write to aux"
I had seen that before
the solution is to edit the system.ini file
add the following lines to it
[Debug]
OutputTo=nul
this disables debug messages, and voila, suddenly the game works
something tells me I already solved that issue in the past
but when I re-set the game up I reintroduced the error

**Comment by exoscoriae** [comment]
Thanks for that. I honestly think I need to apply that to the base windows template. It seems to affect a ton of games.
