### ISSUE TITLE
eXoDOS & eXoWin3x merge issue

### ISSUE THREAD

**Issue by Python-Exoproject** [exoscoriae/eXoWin3x#98]
Just an FYI that I noticed that the current win3x dosbox version in the ece_svn folder is much older than the one in exodos ece_svn folder.

And that the rev0 folder in the mt32 directory of win3x still has the non rev0 CM32 roms in it that we removed from exodos equivalent folder.

Lastly the scummvm folder of win3x has a very old version. Are there any scummvm compatible games in the win3x pack? If not maybe we should just remove scummvm folder from win3x?

**Comment by exoscoriae** [comment]
I haven't repacked all that stuff yet.

But this is a good reminder that it needs to be done.

**Comment by exoscoriae** [comment]
I've fixed and replaced the dosbox and scummvm folders in the util.zip file. That said, I am guessing the util.zip file will need to be renamed.

There are ScummVM games, such as King's Quest and Leisure Suit Larry. However, I don't believe they are currently even setup to use scummvm?

the primary reason scummvm exists here is because the last time I released win3x, the util.zip file was identical to the one in eXoDOS v3

the idea was it didn't matter which set you had, they could both use it. I have a feeling this will no longer be the case. First of all, we have the new svn build we need for JttCotE, and that is not in eXoDOS v5's util.zip file.

Maybe win3x starts using util3x.zip?

I've cleaned up the win3x util file, renamed it, and removed a ton of stuff from it.

We can add scummvm back in if we add support for those games at some point.

**Comment by Python-Exoproject** [comment]
Looks good. The only comment I have left for this stuff is that Win3x uses a new svn release in the dosbox\svn2 folder for JTTCOTE, but the same folder exists in the exodos collection with an older version of svn. 

If someone installed win3x then exodos this would be overwritten and break JTTCOTE. I looked exodos over and no game uses the dosbox found in its dosbox\svn2 folder, the only reference I found was from Theme Park and its rem'd out there. So we could safely update exodos \svn2 folder with the same version now in win3x to avoid the problem.

**Comment by exoscoriae** [comment]
Well, the thing is, even if we update eXoDOS with the new version, eXoDOS v6 won't release before this. So.... someone who goes and gets v5 after installing would still get the old svn2. So you are right, that is problematic.

I suppose the svn2 folder in win3x needs to be renamed, and then JttCotE needs to be repointed to it.

This does bring up a thought I've had lately.... of renaming the existing svn folder to daum, to properly label it for what it is. 

I've renamed svn2 to svn_2 for now, and repacked the dosbox.zip file in the util.zip file.
